name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: all
          - os: macos-latest
            target: all
          - os: windows-latest
            target: ALL_BUILD
    env:
      build_dir: "build"
      config: "Release"
    steps:
      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y cmake gcc g++
      - uses: actions/checkout@v1
      - name: Configure
        run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }} -DTTT_DEPLOY=1
      - name: Build
        run: cmake --build ${{ env.build_dir }} --target ${{ matrix.target }} --verbose -j --config ${{ env.config }}
